
---
- name: Testing copy of the local to remote file
  become: true
  copy:
        src: artifact.tar.gz
        dest: /home/ubuntu

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract 'artifact.tar.gz'
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: install deps
  apt:
  name: npm pm2

- name: Executing node
  become: true
  shell: |   
    echo -e "NODE_ENV=local \n
    VERSION=1\n
    TYPEORM_CONNECTION=postgres\n
    TYPEORM_MIGRATIONS_DIR=./src/migrations\n
    TYPEORM_ENTITIES=./src/modules/domain/*/*/*.entity.ts\n
    TYPEORM_MIGRATIONS=./src/migrations/*.ts\n" > .env

    echo -e "TYPEORM_HOST=$TYPEORM_HOST\n
    TYPEORM_PORT=$TYPEORM_PORT\n
    TYPEORM_USERNAME=§TYPEORM_USERNAME\n
    TYPEORM_PASSWORD=§TYPEORM_PASSWORD\n
    TYPEORM_DATABASE=$TYPEORM_DATABASE\n >> .env
    
    cd /home/ubuntu/backend
    npm install
    npm run build   
    pm2 stop default
    pm2 start npm --name "backend" -- start